services:
  - type: web
    name: lawve-flask-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        value: 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
